### ISSUE TITLE
Some language names not displayed on Win10 Enterprise

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-windows#25] opened 2020-11-23 08:58 UTC
![image](https://user-images.githubusercontent.com/1255285/99944124-0bf89580-2d7b-11eb-8c37-85c75ab7a97c.png)

Windows version:

![image](https://user-images.githubusercontent.com/1255285/99944190-1d41a200-2d7b-11eb-8325-663d4af7550b.png)

**Comment by bbqsrc** [comment] 2020-11-23 09:02
Don't put your OS in a language that isn't English :D

**Comment by snomos** [comment] 2020-11-23 09:06
> Don't put your OS in a language that isn't English :D

These are autonyms, so OS language should just shut up 🗡️ 😄

**Comment by Trondtr** [comment] 2020-11-23 09:07
The problem is that the language shown for the languages that work is *not* english, it is the native language. The only non-english part of the game is "Ukjent språk", which the system is quite capable of stating. When things work, it says things like "kalaallisut", "esperanto", "English", "euskara", "suomi", "føroyskt". Thus, the reason for the behaviour is not missing localisation to languages other than English, but a failure of giving the native language.

**Comment by snomos** [comment] 2020-11-23 09:13
On Windows 10 Home, this works fine:

![](https://user-images.githubusercontent.com/1255285/99942996-3ea18e80-2d79-11eb-8065-9bcab2959e0a.png)

Windows version:

![Bilde 23 11 2020 klokken 11 12](https://user-images.githubusercontent.com/1255285/99945196-df457d80-2d7c-11eb-88ac-f9f2d1b56ea9.jpg)

**Comment by snomos** [comment] 2020-11-23 09:14
Both Windows's referenced are the 2004 update.

**Comment by Trondtr** [comment] 2020-11-23 09:20
My Win machine had not been in use for a while, and now went into a System Update. Perhaps it will help, so just wait with this one until new reports. In any case, this is of course less important than having the updated spellers in the installer.

**Comment by Trondtr** [comment] 2020-12-02 15:13
It did not help. But since it works for others, we close this bug.

**Closed by Trondtr** 2020-12-02 15:13 UTC
Labels: bug

**Comment by snomos** [comment] 2020-12-02 16:11
You can't trust Windows. It will be solved in the next version of Divvun Manager.
